version: "3"

services:
  swaggerql:
    image: swaggerql/swaggerql-mariadb
    depends_on:
    - db
    ports:
    - "8000:8000"
    volumes:
    - ./config/local.yaml:/app/config/local.yaml
    - ./openapi.yaml:/app/openapi.yaml
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
    volumes:
    - ./scripts/00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
    - db-mariadb:/var/lib/mysql
    ports:
    - "3306:3306"
volumes:
  db-mariadb:
