---
openapi: "3.0.1"
info:
  title: Demo
  version: "1.0.0"

paths:
  /test:
    get:
      summary: 1 + n
      description: |
        Adds a number to one

        ```sql
        SELECT 1+:n
        ```
      parameters:
      - name: n
        in: query
        description: Number
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        200:
          description: OK
