---
openapi: "3.0.1"
info:
  title: Demo
  version: "0.0.1"

paths:
  /two:
    get:
      summary: One plus one equals two
      description: |
        SELECT 1+1
      responses:
        200:
          description: OK
  /tables:
    get:
      summary: Show tables
      description: |
        SELECT * FROM pg_catalog.pg_tables
      responses:
        200:
          description: OK
  /test:
    get:
      summary: Test
      description: |
        SELECT
            ROUND((SYSDATE - date '1970-01-01')*24*60*60/3600)*3600 as t,
            to_date(:date, 'YYYYMMDD') + (1/24/60/60) * :timestamp,
            1 + :timestamp as a,
            :date as b,
            SYSDATE
        FROM dual
      parameters:
      - name: timestamp
        in: query
        description: Time in seconds
        required: true
        schema:
          type: integer
        example: 1569153600
      - name: date
        in: query
        description: Date
        required: true
        schema:
          type: string
        example: "19700101"
      responses:
        200:
          description: OK
