version: "3"

services:
  swaggerql:
    image: swaggerql/swaggerql-postgres
    depends_on:
    - db
    ports:
    - "8000:8000"
    volumes:
    - ./config/local.yaml:/app/config/local.yaml
    - ./openapi.yaml:/app/openapi.yaml
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: petstore
    volumes:
    - ./scripts/00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
    - db-postgresql:/var/lib/postgresql/data
    ports:
    - "5432:5432"
volumes:
  db-postgresql:
