version: "3"

services:
  swaggerql:
    image: swaggerql/swaggerql-mysql
    depends_on:
    - db
    ports:
    - "8000:8000"
    volumes:
    - ./config/local.yaml:/app/config/local.yaml
    - ./openapi.yaml:/app/openapi.yaml
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
    volumes:
    - ./scripts/00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
    - db-mysql:/var/lib/mysql
    ports:
    - "33060:33060"
volumes:
  db-mysql:
