version: "3"

services:
  swaggerql:
    image: swaggerql/swaggerql-oracle
    depends_on:
    - db
    ports:
    - "8000:8000"
    volumes:
    - ./config/local.yaml:/app/config/local.yaml
    - ./openapi.yaml:/app/openapi.yaml
  db:
    image: store/oracle/database-enterprise:12.2.0.1-slim
    volumes:
    - ./setup/tnsentry.sh:/home/oracle/setup/tnsentry.sh
    - ./scripts:/scripts
    - db-oracle:/ORCL
    ports:
    - "1521:1521"
volumes:
  db-oracle:
