version: "3"

services:
  swaggerql:
    image: swaggerql/swaggerql-sqlite
    depends_on:
    - init_db
    ports:
    - "8000:8000"
    volumes:
    - ./config/local.yaml:/app/config/local.yaml
    - ./openapi.yaml:/app/openapi.yaml
    - db-sqlite:/data
  init_db:
    image: sstc/sqlite3
    command: /initdb.sh
    volumes:
    - ./scripts/initdb.sh:/initdb.sh
    - ./scripts/00_init.sql:/scripts/00_init.sql
    - db-sqlite:/data
volumes:
  db-sqlite:
